sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: wxf48f03033802b2a0
    secret: 558935a14bfe724127c44b7ea6236adf